name: ci
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt  # Ensure all dependencies are installed
      # - run: pip install mkdocs # Ensure mkdocs is installed
      # - run: pip install mkdocs-slides  # Explicitly install the slides plugin
      # - run: pip install mkdocs-material pillow cairosvg  # Ensure other dependencies are installed
      # Debugging step: Check installed packages
      - run: pip list
      - run: mkdocs gh-deploy --force